#!/usr/bin/env python3
"""LiteKern X - build step: assets/cursors.json + PNGs -> C source for the kernel.

Usage: python3 tools/cursors2c.py assets/cursors.json OUT.c

Every cursor listed in cursors.json becomes 0xAARRGGBB pixel arrays (one per
animation frame) and an entry in `cursor_shapes[]` (kernel/cursor.h). The
build fails with a clear message if a file is missing, isn't 32x32 RGBA, or
a hotspot isn't on an opaque pixel (docs/ASSET-PROMPTS.md §3).
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lkx_png import read_rgba  # noqa: E402

SIZE = 32


def fail(msg):
    sys.exit(f"cursors2c: {msg}")


def main():
    if len(sys.argv) != 3:
        fail("usage: cursors2c.py assets/cursors.json OUT.c")
    spec_path, out_path = sys.argv[1], sys.argv[2]
    base = os.path.join(os.path.dirname(spec_path), "cursors")
    spec = json.load(open(spec_path, encoding="utf-8"))
    if spec.get("version") != 1 or spec.get("size") != SIZE:
        fail(f"{spec_path}: expected version 1, size {SIZE}")

    arrays, entries = [], []
    for name, c in spec["cursors"].items():
        if not re.fullmatch(r"[a-z0-9-]+", name):
            fail(f"bad cursor name {name!r}")
        files = c.get("frames") or [c.get("file")]
        if not all(files):
            fail(f"{name}: needs \"file\" or \"frames\"")
        hx, hy = c.get("hotspot", [None, None])
        if not (isinstance(hx, int) and isinstance(hy, int) and 0 <= hx < SIZE and 0 <= hy < SIZE):
            fail(f"{name}: hotspot must be two whole numbers from 0 to {SIZE - 1}")
        frame_ids = []
        for i, f in enumerate(files):
            path = os.path.join(base, f)
            if not os.path.exists(path):
                fail(f"{name}: {path} not found")
            w, h, px = read_rgba(path)
            if (w, h) != (SIZE, SIZE):
                fail(f"{path}: is {w}x{h}, must be {SIZE}x{SIZE}")
            if px[hy][hx][3] != 255:
                fail(f"{path}: hotspot {hx},{hy} is not an opaque pixel")
            ident = f"{name.replace('-', '_')}_{i}"
            vals = [(a << 24) | (r << 16) | (g << 8) | b for row in px for (r, g, b, a) in row]
            body = ",\n".join("    " + ", ".join(f"0x{v:08x}" for v in vals[k:k + 8])
                              for k in range(0, len(vals), 8))
            arrays.append(f"static const uint32_t px_{ident}[{SIZE * SIZE}] = {{\n{body}\n}};\n")
            frame_ids.append(f"px_{ident}")
        arrays.append(f"static const uint32_t *const frames_{name.replace('-', '_')}[] = "
                      f"{{ {', '.join(frame_ids)} }};\n")
        entries.append(f'    {{ "{name}", {SIZE}, {SIZE}, {hx}, {hy}, {len(files)}, '
                       f'{int(c.get("frame_ms", 0))}, frames_{name.replace("-", "_")} }},')

    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("/* Generated by tools/cursors2c.py from assets/cursors.json. Do not edit. */\n")
        out.write('#include "kernel/cursor.h"\n\n')
        out.write("\n".join(arrays))
        out.write("\nconst struct cursor_shape cursor_shapes[] = {\n")
        out.write("\n".join(entries))
        out.write(f"\n}};\nconst int cursor_shape_count = {len(entries)};\n")
    print(f"cursors2c: {len(entries)} cursor(s) -> {out_path}")


if __name__ == "__main__":
    main()
