#!/usr/bin/env python3
"""LiteKern X - build step: the GUI font atlas -> C (kernel/text.h).

Usage: python3 tools/font2c.py assets/fonts/ui-font.json OUT.c

Reads ui-font.json and ui-font.png (made by tools/font-rasterize.py) and
writes each face's metrics, glyph table and 8-bit coverage, one array per
face. Standard library only (tools/lkx_png.py reads the PNG).
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lkx_png import read_rgba  # noqa: E402


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: font2c.py ui-font.json OUT.c")
    meta = json.load(open(sys.argv[1], encoding="utf-8"))
    w, h, px = read_rgba(os.path.join(os.path.dirname(sys.argv[1]), "ui-font.png"))
    out = ['/* Generated by tools/font2c.py from assets/fonts/ui-font.*. Do not edit. */',
           '#include "kernel/text.h"', ""]
    faces = []
    for fi, face in enumerate(meta["faces"]):
        cov, glyphs = [], []
        for g in face["glyphs"]:
            off = len(cov)
            for y in range(g["h"]):
                for x in range(g["w"]):
                    cov.append(px[g["y"] + y][g["x"] + x][0])
            glyphs.append(f'    {{ {g["w"]}, {g["h"]}, {g["xoff"]}, {g["yoff"]}, {g["adv64"]}, {off} }},')
        body = ",\n".join("    " + ", ".join(str(v) for v in cov[k:k + 24]) for k in range(0, len(cov), 24))
        out.append(f"static const uint8_t cov_{fi}[{max(len(cov), 1)}] = {{\n{body or '    0'}\n}};")
        out.append(f"static const struct text_glyph glyphs_{fi}[{len(glyphs)}] = {{\n" + "\n".join(glyphs) + "\n};")
        faces.append(f'    {{ "{face["name"]}", {face["size"]}, {face["ascent"]}, {face["descent"]}, '
                     f'glyphs_{fi}, cov_{fi} }},')
    out.append("const struct text_face text_faces[TEXT_FACES] = {\n" + "\n".join(faces) + "\n};")
    with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"font2c: {len(faces)} faces -> {sys.argv[2]}")


if __name__ == "__main__":
    main()
