#!/usr/bin/env python3
"""LiteKern X - build step: assets/icons.json + PNGs -> C source for the kernel.

Usage: python3 tools/icons2c.py assets/icons.json OUT.c

Every icon listed in icons.json becomes a 0xAARRGGBB pixel array and an
entry in `icons[]` (kernel/icon.h). The build fails with a clear message if
a file is missing or isn't 48x48 RGBA (docs/ASSET-PROMPTS.md §2).
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lkx_png import read_rgba  # noqa: E402

SIZE = 48


def fail(msg):
    sys.exit(f"icons2c: {msg}")


def main():
    if len(sys.argv) != 3:
        fail("usage: icons2c.py assets/icons.json OUT.c")
    spec_path, out_path = sys.argv[1], sys.argv[2]
    base = os.path.join(os.path.dirname(spec_path), "icons")
    spec = json.load(open(spec_path, encoding="utf-8"))
    if spec.get("version") != 1 or spec.get("size") != SIZE:
        fail(f"{spec_path}: expected version 1, size {SIZE}")

    arrays, entries = [], []
    for name, file in spec["icons"].items():
        if not re.fullmatch(r"[a-z0-9-]+", name):
            fail(f"bad icon name {name!r}")
        path = os.path.join(base, file)
        if not os.path.exists(path):
            fail(f"{name}: {path} not found")
        w, h, px = read_rgba(path)
        if (w, h) != (SIZE, SIZE):
            fail(f"{path}: is {w}x{h}, must be {SIZE}x{SIZE}")
        ident = name.replace("-", "_")
        vals = [(a << 24) | (r << 16) | (g << 8) | b for row in px for (r, g, b, a) in row]
        body = ",\n".join("    " + ", ".join(f"0x{v:08x}" for v in vals[k:k + 8])
                          for k in range(0, len(vals), 8))
        arrays.append(f"static const uint32_t px_{ident}[{SIZE * SIZE}] = {{\n{body}\n}};\n")
        entries.append(f'    {{ "{name}", {SIZE}, {SIZE}, px_{ident} }},')

    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("/* Generated by tools/icons2c.py from assets/icons.json. Do not edit. */\n")
        out.write('#include "kernel/icon.h"\n\n')
        out.write("\n".join(arrays))
        out.write("\nconst struct icon icons[] = {\n")
        out.write("\n".join(entries))
        out.write(f"\n}};\nconst int icon_count = {len(entries)};\n")
    print(f"icons2c: {len(entries)} icon(s) -> {out_path}")


if __name__ == "__main__":
    main()
